version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_URI=mongodb+srv://dgupta0602_db_user:qWKqJwkt0F151FME@cluster0.m5jijs7.mongodb.net/?appName=Cluster0

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend